# Generated by Django 4.2.6 on 2023-10-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileExchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('code', models.CharField(max_length=128)),
                ('creation_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'file_exchange',
            },
        ),
    ]
