# Generated by Django 4.2.6 on 2023-10-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileexchange',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
