# Generated by Django 4.2.6 on 2023-10-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_alter_fileexchange_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileexchange',
            name='downloaded',
            field=models.BooleanField(default=0),
        ),
    ]
